#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#
# esapy_rpc documentation build configuration file, created by
# sphinx-quickstart on Tue Nov 21 09:37:42 2017.
#
# This file is execfile()d with the current directory set to its
# containing dir.
#
# Note that not all possible configuration values are present in this
# autogenerated file.
#
# All configuration values have a default; values that are commented out
# serve to show the default.

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

from pathlib import Path

import sphinx_rtd_theme
from setuptools.config import read_configuration

numfig = True
numfig_format = {
    "figure": "Figure %s",
    "table": "Table %s",
    "code-block": "Listing %s",
    "section": "Section %s",
}

# ROOT_DIR = path.dirname(path.dirname(path.dirname(path.abspath(__file__))))
# PROJ_NAME = path.split(ROOT_DIR)[1]
# SRC_DIR = ROOT_DIR  # path.join(ROOT_DIR, PROJ_NAME)
# print('Adding project source directory to PYTHON_PATH: %s' % SRC_DIR)
# sys.path.append(SRC_DIR)

print("Imported package: SolarY")

plantuml = "java -jar /usr/local/plantuml/plantuml.jar"

# Read 'setup.cfg' file
parent_folder = Path(__file__).parent
setup_cfg_filename = parent_folder.joinpath("../../setup.cfg").resolve(
    strict=True
)  # type: Path
metadata = read_configuration(setup_cfg_filename)["metadata"]  # type: dict


# -- General configuration ------------------------------------------------

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# extensions = ['sphinx.ext.autodoc']
extensions = [
    "sphinx.ext.autodoc",  # include documentation from docstrings
    # 'sphinx.ext.todo',          # support for todo items (.. todo::)
    # 'sphinx.ext.coverage',      # collect doc coverage stats
    # 'sphinx.ext.mathjax',       # render math via Javascript
    # 'sphinx.ext.viewcode',      # add links to highlighted source code
    # 'sphinx.ext.autosummary',   # Generate autodoc summaries
    # 'sphinx.ext.autosectionlabel',
    "numpydoc",
    "sphinx_autodoc_typehints",
    # 'sphinx_autodoc_napoleon_typehints',
    # 'sphinx.ext.napoleon'       # Support for NumPy and Google style docstrings
    # 'sphinxcontrib.plantuml',
    # 'sphinxcontrib.mermaid',
    # 'sphinx.ext.numfig',
    # 'rst2pdf.pdfbuilder',
]
autosectionlabel_prefix_document = True
set_type_checking_flag = True
# typehints_fully_qualified = True
# always_document_param_types = True
# typehints_document_rtype = True

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
# source_suffix = ['.rst', '.md']
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# General information about the project.
project = metadata["name"]
author = metadata["author"]
title = project.title() + " User Manual"

# The version info for the project you're documenting, acts as replacement for
# |version| and |release|, also used in various other places throughout the
# built documents.
#
# The short X.Y version.
version = metadata["version"]
# The full version, including alpha/beta/rc tags.
release = metadata["version"].split("+", 1)[0]

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = None

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This patterns also effect to html_static_path and html_extra_path
exclude_patterns = ["_build", "Thumbs.db", ".DS_Store"]

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# If true, `todo` and `todoList` produce output, else they produce nothing.
todo_include_todos = False


# -- Options for HTML output ----------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
html_theme = "sphinx_rtd_theme"  # 'alabaster'
html_theme_path = [sphinx_rtd_theme.get_html_theme_path()]

# Theme options are theme-specific and customize the look and feel of a theme
# further.  For a list of options available for each theme, see the
# documentation.
#
# html_theme_options = {}

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
html_static_path = ["_static"]

# Custom sidebar templates, must be a dictionary that maps document names
# to template names.
#
# This is required for the alabaster theme
# refs: http://alabaster.readthedocs.io/en/latest/installation.html#sidebars
html_sidebars = {
    "**": [
        "relations.html",  # needs 'show_related': True theme option to display
        "searchbox.html",
    ]
}


# -- Options for HTMLHelp output ------------------------------------------

# Output file base name for HTML help builder.
htmlhelp_basename = metadata["name"] + "doc"


# -- Options for LaTeX output ---------------------------------------------

latex_elements = {
    # The paper size ('letterpaper' or 'a4paper').
    #
    # 'papersize': 'letterpaper',
    # The font size ('10pt', '11pt' or '12pt').
    #
    # 'pointsize': '10pt',
    # Additional stuff for the LaTeX preamble.
    #
    # 'preamble': '',
    # Latex figure (float) alignment
    #
    # 'figure_align': 'htbp',
}

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title,
#  author, documentclass [howto, manual, or own class]).
latex_documents = [
    (master_doc, project + ".tex", title, author, "manual"),
]


# -- Options for manual page output ---------------------------------------

# One entry per manual page. List of tuples
# (source start file, name, description, authors, manual section).
man_pages = [(master_doc, project, title, [author], 1)]


# -- Options for Texinfo output -------------------------------------------

# Grouping the document tree into Texinfo files. List of tuples
# (source start file, target name, title, author,
#  dir menu entry, description, category)
texinfo_documents = [
    (
        master_doc,
        project,
        title,
        author,
        project,
        "One line description of project.",
        "Miscellaneous",
    ),
]


# def setup(app):
#     app.add_stylesheet('custom.css')
